"""CCF-A 会议 / 期刊目录（数据快照，由 ``scripts/gen_ccf_catalog.py`` 生成）。

来源与可信度
------------
* **会议**：`ccfddl.com <https://ccfddl.com/>`_ 的公开 RSS
  （``/conference/deadlines_en.xml``）。每条都带 CCF 等级、领域、官网与 DBLP 索引，
  同一会议取**最新一届**的官网（即当前真正在线的那个）。ccfddl 只收录公布了截稿
  日期的会议，因此 **VLDB / PODS / ICFP 等未收录的 A 类会议由人工补充**。
* **期刊**：没有任何截稿站收录期刊，因此 A 类期刊全部来自人工整理
  （依据 CCF 推荐国际学术期刊目录）。**这是目录里最可能出错的部分** ——
  发现错误请直接在 `ccf.md` 里取消勾选或删除，并提交 issue。

所有 URL 在生成时都经过真实 HTTP 校验。本文件是**快照**：
运行 ``python scripts/gen_ccf_catalog.py`` 可重新抓取并覆盖它。

生成时间：2026-09-14
"""

from __future__ import annotations

CCF_CATALOG_VERSION = '2026-09-14'
CCF_CATALOG_SOURCE = "ccfddl.com RSS + curated supplement"

#: CCF-A 会议（71 个）
CCF_A_CONFERENCES: list[dict[str, str]] = [
    {
        "name": 'AAAI',
        "full": 'AAAI Conference on Artificial Intelligence',
        "area": '人工智能 (AI)',
        "homepage": 'https://aaai.org/conference/aaai/aaai-27/',
        "dblp": 'https://dblp.org/db/conf/aaai',
        "ccf": 'A',
    },
    {
        "name": 'ACL',
        "full": 'Annual Meeting of the Association for Computational Linguistics',
        "area": '人工智能 (AI)',
        "homepage": 'https://2026.aclweb.org/',
        "dblp": 'https://dblp.org/db/conf/acl',
        "ccf": 'A',
    },
    {
        "name": 'ACM MM',
        "full": 'ACM International Conference on Multimedia',
        "area": '计算机图形学与多媒体 (CG)',
        "homepage": 'https://2026.acmmm.org/',
        "dblp": 'https://dblp.org/db/conf/mm',
        "ccf": 'A',
    },
    {
        "name": 'ACM SIGGRAPH',
        "full": 'ACM SIGGRAPH Annual Conference',
        "area": '计算机图形学与多媒体 (CG)',
        "homepage": 'https://s2026.siggraph.org/',
        "dblp": 'https://dblp.org/db/conf/siggraph',
        "ccf": 'A',
    },
    {
        "name": 'ASE',
        "full": 'International Conference on Automated Software Engineering',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://conf.researchr.org/home/ase-2026',
        "dblp": 'https://dblp.org/db/conf/kbse',
        "ccf": 'A',
    },
    {
        "name": 'ASPLOS',
        "full": 'International Conference on Architectural Support for Programming Languages and Operating Systems',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.asplos-conference.org/asplos2027/cfp/',
        "dblp": 'https://dblp.org/db/conf/asplos',
        "ccf": 'A',
    },
    {
        "name": 'CAV',
        "full": 'International Conference on Computer-Aided Verification',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://conferences.i-cav.org/2027/',
        "dblp": 'https://dblp.org/db/conf/cav',
        "ccf": 'A',
    },
    {
        "name": 'CCS',
        "full": 'ACM Conference on Computer and Communications Security',
        "area": '网络与信息安全 (SC)',
        "homepage": 'https://www.sigsac.org/ccs/CCS2026/',
        "dblp": 'https://dblp.org/db/conf/ccs',
        "ccf": 'A',
    },
    {
        "name": 'CHI',
        "full": 'ACM Conference on Human Factors in Computing Systems',
        "area": '人机交互与普适计算 (HI)',
        "homepage": 'https://chi2027.acm.org/',
        "dblp": 'https://dblp.org/db/conf/chi',
        "ccf": 'A',
    },
    {
        "name": 'CRYPTO',
        "full": 'International Cryptology Conference',
        "area": '网络与信息安全 (SC)',
        "homepage": 'https://crypto.iacr.org/2026/',
        "dblp": 'https://dblp.org/db/conf/crypto',
        "ccf": 'A',
    },
    {
        "name": 'CSCW',
        "full": 'ACM Conference on Computer Supported Cooperative Work and Social Computing',
        "area": '人机交互与普适计算 (HI)',
        "homepage": 'https://cscw.acm.org/2026/',
        "dblp": 'https://dblp.org/db/conf/cscw',
        "ccf": 'A',
    },
    {
        "name": 'CVPR',
        "full": 'IEEE/CVF Conference on Computer Vision and Pattern Recognition',
        "area": '人工智能 (AI)',
        "homepage": 'https://cvpr.thecvf.com/Conferences/2027',
        "dblp": 'https://dblp.org/db/conf/cvpr',
        "ccf": 'A',
    },
    {
        "name": 'DAC',
        "full": 'Design Automation Conference',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://dac.com/2027/authors/call-for-contributions',
        "dblp": 'https://dblp.org/db/conf/dac',
        "ccf": 'A',
    },
    {
        "name": 'DATE',
        "full": 'Design, Automation and Test in Europe',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.date-conference.com/',
        "dblp": 'https://dblp.org/db/conf/date',
        "ccf": 'A',
    },
    {
        "name": 'DISC',
        "full": 'International Symposium on Distributed Computing',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://www.disc-conference.org/',
        "dblp": 'https://dblp.org/db/conf/wdag',
        "ccf": 'A',
    },
    {
        "name": 'ECCV',
        "full": 'European Conference on Computer Vision',
        "area": '人工智能 (AI)',
        "homepage": 'https://eccv.ecva.net/',
        "dblp": 'https://dblp.org/db/conf/eccv',
        "ccf": 'A',
    },
    {
        "name": 'EMNLP',
        "full": 'Conference on Empirical Methods in Natural Language Processing',
        "area": '人工智能 (AI)',
        "homepage": 'https://aclanthology.org/venues/emnlp/',
        "dblp": 'https://dblp.org/db/conf/emnlp',
        "ccf": 'A',
    },
    {
        "name": 'EUROCRYPT',
        "full": 'European Cryptology Conference',
        "area": '网络与信息安全 (SC)',
        "homepage": 'https://eurocrypt.iacr.org/2027/',
        "dblp": 'https://dblp.org/db/conf/eurocrypt',
        "ccf": 'A',
    },
    {
        "name": 'EuroSys',
        "full": 'European Conference on Computer Systems',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://2027.eurosys.org/',
        "dblp": 'https://dblp.org/db/conf/eurosys',
        "ccf": 'A',
    },
    {
        "name": 'FAST',
        "full": 'USENIX Conference on File and Storage Technologies',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.usenix.org/conference/fast27',
        "dblp": 'https://dblp.org/db/conf/fast',
        "ccf": 'A',
    },
    {
        "name": 'FM',
        "full": 'International Symposium on Formal Methods',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://conf.researchr.org/home/fm-2026',
        "dblp": 'https://dblp.org/db/conf/fm',
        "ccf": 'A',
    },
    {
        "name": 'FOCS',
        "full": 'IEEE Symposium on Foundations of Computer Science',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://sanjeevkhanna.org/FOCS2026_CFP.html',
        "dblp": 'https://dblp.org/db/conf/focs',
        "ccf": 'A',
    },
    {
        "name": 'FSE',
        "full": 'ACM International Conference on the Foundations of Software Engineering',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://conf.researchr.org/home/fse-2027',
        "dblp": 'https://dblp.org/db/conf/sigsoft',
        "ccf": 'A',
    },
    {
        "name": 'HPCA',
        "full": 'IEEE International Symposium on High-Performance Computer Architecture',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://conf.researchr.org/home/hpca-2027',
        "dblp": 'https://dblp.org/db/conf/hpca',
        "ccf": 'A',
    },
    {
        "name": 'HPDC',
        "full": 'ACM Symposium on High-Performance Parallel and Distributed Computing',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://hpdc.sci.utah.edu/2026/',
        "dblp": 'https://dblp.org/db/conf/hpdc',
        "ccf": 'A',
    },
    {
        "name": 'ICCAD',
        "full": 'International Conference on Computer-Aided Design',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.iccad.com/',
        "dblp": 'https://dblp.org/db/conf/iccad',
        "ccf": 'A',
    },
    {
        "name": 'ICCV',
        "full": 'IEEE International Conference on Computer Vision',
        "area": '人工智能 (AI)',
        "homepage": 'https://iccv.thecvf.com/Conferences/2025',
        "dblp": 'https://dblp.org/db/conf/iccv',
        "ccf": 'A',
    },
    {
        "name": 'ICDE',
        "full": 'IEEE International Conference on Data Engineering',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://icde2027.github.io/',
        "dblp": 'https://dblp.org/db/conf/icde',
        "ccf": 'A',
    },
    {
        "name": 'ICFP',
        "full": 'International Conference on Functional Programming',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://icfpconference.org/',
        "dblp": 'https://dblp.org/db/conf/icfp',
        "ccf": 'A',
    },
    {
        "name": 'ICLR',
        "full": 'International Conference on Learning Representations',
        "area": '人工智能 (AI)',
        "homepage": 'https://iclr.cc/Conferences/2027',
        "dblp": 'https://dblp.org/db/conf/iclr',
        "ccf": 'A',
    },
    {
        "name": 'ICML',
        "full": 'International Conference on Machine Learning',
        "area": '人工智能 (AI)',
        "homepage": 'https://icml.cc/Conferences/2026',
        "dblp": 'https://dblp.org/db/conf/icml',
        "ccf": 'A',
    },
    {
        "name": 'ICSE',
        "full": 'International Conference on Software Engineering',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://conf.researchr.org/home/icse-2027',
        "dblp": 'https://dblp.org/db/conf/icse',
        "ccf": 'A',
    },
    {
        "name": 'IEEE VIS',
        "full": 'IEEE Visualization Conference',
        "area": '计算机图形学与多媒体 (CG)',
        "homepage": 'https://ieeevis.org/year/2026/welcome',
        "dblp": 'https://dblp.org/db/conf/visualization',
        "ccf": 'A',
    },
    {
        "name": 'IEEE VR',
        "full": 'IEEE Virtual Reality',
        "area": '计算机图形学与多媒体 (CG)',
        "homepage": 'https://ieeevr.org/2027/',
        "dblp": 'https://dblp.org/db/conf/vr',
        "ccf": 'A',
    },
    {
        "name": 'IJCAI',
        "full": 'International Joint Conference on Artificial Intelligence',
        "area": '人工智能 (AI)',
        "homepage": 'https://www.ijcai.org/',
        "dblp": 'https://dblp.org/db/conf/ijcai',
        "ccf": 'A',
    },
    {
        "name": 'INFOCOM',
        "full": 'IEEE International Conference on Computer Communications',
        "area": '计算机网络 (NW)',
        "homepage": 'https://infocom2027.ieee-infocom.org/',
        "dblp": 'https://dblp.org/db/conf/infocom',
        "ccf": 'A',
    },
    {
        "name": 'IPDPS',
        "full": 'IEEE International Parallel and Distributed Processing Symposium',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.ipdps.org/',
        "dblp": 'https://dblp.org/db/conf/ipps',
        "ccf": 'A',
    },
    {
        "name": 'ISCA',
        "full": 'International Symposium on Computer Architecture',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://iscaconf.org/isca2026/',
        "dblp": 'https://dblp.org/db/conf/isca',
        "ccf": 'A',
    },
    {
        "name": 'ISSTA',
        "full": 'ACM SIGSOFT International Symposium on Software Testing and Analysis',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://conf.researchr.org/home/issta-2027',
        "dblp": 'https://dblp.org/db/conf/issta',
        "ccf": 'A',
    },
    {
        "name": 'LICS',
        "full": 'IEEE Symposium on Logic in Computer Science',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://lics.siglog.org/lics26/',
        "dblp": 'https://dblp.org/db/conf/lics',
        "ccf": 'A',
    },
    {
        "name": 'MICRO',
        "full": 'IEEE/ACM International Symposium on Microarchitecture',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://microarch.org/micro59/',
        "dblp": 'https://dblp.org/db/conf/micro',
        "ccf": 'A',
    },
    {
        "name": 'MobiCom',
        "full": 'ACM Annual International Conference On Mobile Computing And Networking',
        "area": '计算机网络 (NW)',
        "homepage": 'https://www.sigmobile.org/mobicom/2027/',
        "dblp": 'https://dblp.org/db/conf/mobicom',
        "ccf": 'A',
    },
    {
        "name": 'NAACL',
        "full": 'Annual Conference of the North American Chapter of the Association for Computational Linguistics',
        "area": '人工智能 (AI)',
        "homepage": 'https://aclanthology.org/venues/naacl/',
        "dblp": 'https://dblp.org/db/conf/naacl',
        "ccf": 'A',
    },
    {
        "name": 'NDSS',
        "full": 'Network and Distributed System Security (NDSS) Symposium',
        "area": '网络与信息安全 (SC)',
        "homepage": 'https://www.ndss-symposium.org/ndss2027/',
        "dblp": 'https://dblp.org/db/conf/ndss',
        "ccf": 'A',
    },
    {
        "name": 'NeurIPS',
        "full": 'Conference on Neural Information Processing Systems',
        "area": '人工智能 (AI)',
        "homepage": 'https://neurips.cc/Conferences/2026',
        "dblp": 'https://dblp.org/db/conf/nips',
        "ccf": 'A',
    },
    {
        "name": 'NSDI',
        "full": 'USENIX Symposium on Networked Systems Design and Implementation',
        "area": '计算机网络 (NW)',
        "homepage": 'https://www.usenix.org/conference/nsdi27',
        "dblp": 'https://dblp.org/db/conf/nsdi',
        "ccf": 'A',
    },
    {
        "name": 'OOPSLA',
        "full": 'Conference on Object-Oriented Programming Systems, Languages, and Applications',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://conf.researchr.org/track/splash-2026/oopsla-2026',
        "dblp": 'https://dblp.org/db/conf/oopsla',
        "ccf": 'A',
    },
    {
        "name": 'OSDI',
        "full": 'USENIX Symposium on Operating Systems Design and Implementation',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://www.usenix.org/conference/osdi27',
        "dblp": 'https://dblp.org/db/conf/osdi',
        "ccf": 'A',
    },
    {
        "name": 'PLDI',
        "full": 'ACM SIGPLAN Conference on Programming Language Design & Implementation',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://pldi27.sigplan.org/',
        "dblp": 'https://dblp.org/db/conf/pldi',
        "ccf": 'A',
    },
    {
        "name": 'PODC',
        "full": 'ACM Symposium on Principles of Distributed Computing',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://www.podc.org/',
        "dblp": 'https://dblp.org/db/conf/podc',
        "ccf": 'A',
    },
    {
        "name": 'PODS',
        "full": 'ACM Symposium on Principles of Database Systems',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://sigmod.org/pods/',
        "dblp": 'https://dblp.org/db/conf/pods',
        "ccf": 'A',
    },
    {
        "name": 'POPL',
        "full": 'ACM SIGPLAN-SIGACT Symposium on Principles of Programming Languages',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://popl27.sigplan.org/',
        "dblp": 'https://dblp.org/db/conf/popl',
        "ccf": 'A',
    },
    {
        "name": 'PPoPP',
        "full": 'ACM SIGPLAN Symposium on Principles & Practice of Parallel Programming',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://ppopp27.sigplan.org/',
        "dblp": 'https://dblp.org/db/conf/ppopp',
        "ccf": 'A',
    },
    {
        "name": 'RTSS',
        "full": 'The IEEE Real-Time Systems Symposium',
        "area": '交叉/综合/新兴 (MX)',
        "homepage": 'http://2026.rtss.org/',
        "dblp": 'https://dblp.org/db/conf/rtss',
        "ccf": 'A',
    },
    {
        "name": 'S&P',
        "full": 'IEEE Symposium on Security and Privacy',
        "area": '网络与信息安全 (SC)',
        "homepage": 'https://sp2027.ieee-security.org/index.html',
        "dblp": 'https://dblp.org/db/conf/sp',
        "ccf": 'A',
    },
    {
        "name": 'SC',
        "full": 'International Conference for High Performance Computing, Networking, Storage, and Analysis',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://sc26.supercomputing.org/',
        "dblp": 'https://dblp.org/db/conf/sc',
        "ccf": 'A',
    },
    {
        "name": 'SIGCOMM',
        "full": 'ACM International Conference on Applications, Technologies, Architectures, and Protocols for Computer Communication',
        "area": '计算机网络 (NW)',
        "homepage": 'https://conferences.sigcomm.org/sigcomm/2026/',
        "dblp": 'https://dblp.org/db/conf/sigcomm',
        "ccf": 'A',
    },
    {
        "name": 'SIGIR',
        "full": 'International Conference on Research on Development in Information Retrieval',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://sigir2026.org/en-AU',
        "dblp": 'https://dblp.org/db/conf/sigir',
        "ccf": 'A',
    },
    {
        "name": 'SIGKDD',
        "full": 'ACM Knowledge Discovery and Data Mining',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://kdd2027.kdd.org/',
        "dblp": 'https://dblp.org/db/conf/kdd',
        "ccf": 'A',
    },
    {
        "name": 'SIGMETRICS',
        "full": 'ACM SIGMETRICS International Conference on Measurement and Modeling of Computer Systems',
        "area": '计算机网络 (NW)',
        "homepage": 'https://www.sigmetrics.org/',
        "dblp": 'https://dblp.org/db/conf/sigmetrics',
        "ccf": 'A',
    },
    {
        "name": 'SIGMOD',
        "full": 'ACM Conference on Management of Data',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://2027.sigmod.org/',
        "dblp": 'https://dblp.org/db/conf/sigmod',
        "ccf": 'A',
    },
    {
        "name": 'SIGOPS ATC',
        "full": 'ACM SIGOPS Annual Technical Conference',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://sigops.org/s/conferences/atc/2026/index.html',
        "dblp": 'https://dblp.org/db/conf/usenix',
        "ccf": 'A',
    },
    {
        "name": 'SODA',
        "full": 'ACM-SIAM Symposium on Discrete Algorithms',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://www.siam.org/conferences-events/siam-conferences/soda27/',
        "dblp": 'https://dblp.org/db/conf/soda',
        "ccf": 'A',
    },
    {
        "name": 'SOSP',
        "full": 'ACM Symposium on Operating Systems Principles',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://sigops.org/s/conferences/sosp/2026/index.html',
        "dblp": 'https://dblp.org/db/conf/sosp',
        "ccf": 'A',
    },
    {
        "name": 'STOC',
        "full": 'ACM Symposium on the Theory of Computing',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://acm-stoc.org/stoc2026/',
        "dblp": 'https://dblp.org/db/conf/stoc',
        "ccf": 'A',
    },
    {
        "name": 'TACAS',
        "full": 'International Conference on Tools and Algorithms for the Construction and Analysis of Systems',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://www.etaps.org/',
        "dblp": 'https://dblp.org/db/conf/tacas',
        "ccf": 'A',
    },
    {
        "name": 'UbiComp/ISWC',
        "full": 'ACM International Joint Conference on Pervasive and Ubiquitous Computing',
        "area": '人机交互与普适计算 (HI)',
        "homepage": 'https://www.ubicomp.org/ubicomp-iswc-2026',
        "dblp": 'https://dblp.org/db/conf/huc',
        "ccf": 'A',
    },
    {
        "name": 'UIST',
        "full": 'ACM Symposium on User Interface Software and Technology',
        "area": '人机交互与普适计算 (HI)',
        "homepage": 'https://uist.acm.org/2026/',
        "dblp": 'https://dblp.org/db/conf/uist',
        "ccf": 'A',
    },
    {
        "name": 'USENIX Security',
        "full": 'USENIX Security Symposium',
        "area": '网络与信息安全 (SC)',
        "homepage": 'https://www.usenix.org/conference/usenixsecurity27',
        "dblp": 'https://dblp.org/db/conf/uss',
        "ccf": 'A',
    },
    {
        "name": 'VLDB',
        "full": 'International Conference on Very Large Data Bases',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://vldb.org/',
        "dblp": 'https://dblp.org/db/conf/vldb',
        "ccf": 'A',
    },
    {
        "name": 'WWW',
        "full": 'International World Wide Web Conferences',
        "area": '交叉/综合/新兴 (MX)',
        "homepage": 'https://www2027.thewebconf.org/',
        "dblp": 'https://dblp.org/db/conf/www',
        "ccf": 'A',
    },
]

#: CCF-A 期刊（22 个）
CCF_A_JOURNALS: list[dict[str, str]] = [
    {
        "name": 'AIJ',
        "full": 'Artificial Intelligence',
        "area": '人工智能 (AI)',
        "homepage": 'https://www.sciencedirect.com/journal/artificial-intelligence',
        "dblp": '',
        "ccf": 'A',
        "issn": '0004-3702',
    },
    {
        "name": 'JACM',
        "full": 'Journal of the ACM',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://dl.acm.org/journal/jacm',
        "dblp": '',
        "ccf": 'A',
        "issn": '0004-5411',
    },
    {
        "name": 'JMLR',
        "full": 'Journal of Machine Learning Research',
        "area": '人工智能 (AI)',
        "homepage": 'https://www.jmlr.org/',
        "dblp": '',
        "ccf": 'A',
        "issn": '1532-4435',
    },
    {
        "name": 'LMCS',
        "full": 'Logical Methods in Computer Science',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://lmcs.episciences.org/',
        "dblp": '',
        "ccf": 'A',
        "issn": '1860-5974',
    },
    {
        "name": 'TC',
        "full": 'IEEE Transactions on Computers',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.computer.org/csdl/journal/tc',
        "dblp": '',
        "ccf": 'A',
        "issn": '0018-9340',
    },
    {
        "name": 'TCAD',
        "full": 'IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.computer.org/csdl/journal/tcad',
        "dblp": '',
        "ccf": 'A',
        "issn": '0278-0070',
    },
    {
        "name": 'TIFS',
        "full": 'IEEE Transactions on Information Forensics and Security',
        "area": '网络与信息安全 (SC)',
        "homepage": 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10206',
        "dblp": '',
        "ccf": 'A',
        "issn": '1556-6013',
    },
    {
        "name": 'TIP',
        "full": 'IEEE Transactions on Image Processing',
        "area": '计算机图形学与多媒体 (CG)',
        "homepage": 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=83',
        "dblp": '',
        "ccf": 'A',
        "issn": '1057-7149',
    },
    {
        "name": 'TIT',
        "full": 'IEEE Transactions on Information Theory',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=18',
        "dblp": '',
        "ccf": 'A',
        "issn": '0018-9448',
    },
    {
        "name": 'TKDE',
        "full": 'IEEE Transactions on Knowledge and Data Engineering',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://www.computer.org/csdl/journal/tk',
        "dblp": '',
        "ccf": 'A',
        "issn": '1041-4347',
    },
    {
        "name": 'TMC',
        "full": 'IEEE Transactions on Mobile Computing',
        "area": '计算机网络 (NW)',
        "homepage": 'https://www.computer.org/csdl/journal/tm',
        "dblp": '',
        "ccf": 'A',
        "issn": '1536-1233',
    },
    {
        "name": 'TNNLS',
        "full": 'IEEE Transactions on Neural Networks and Learning Systems',
        "area": '人工智能 (AI)',
        "homepage": 'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962385',
        "dblp": '',
        "ccf": 'A',
        "issn": '2162-237X',
    },
    {
        "name": 'TOCHI',
        "full": 'ACM Transactions on Computer-Human Interaction',
        "area": '人机交互与普适计算 (HI)',
        "homepage": 'https://dl.acm.org/journal/tochi',
        "dblp": '',
        "ccf": 'A',
        "issn": '1073-0516',
    },
    {
        "name": 'TOCL',
        "full": 'ACM Transactions on Computational Logic',
        "area": '计算机科学理论 (CT)',
        "homepage": 'https://dl.acm.org/journal/tocl',
        "dblp": '',
        "ccf": 'A',
        "issn": '1529-3785',
    },
    {
        "name": 'TOCS',
        "full": 'ACM Transactions on Computer Systems',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://dl.acm.org/journal/tocs',
        "dblp": '',
        "ccf": 'A',
        "issn": '0734-2071',
    },
    {
        "name": 'TODS',
        "full": 'ACM Transactions on Database Systems',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://dl.acm.org/journal/tods',
        "dblp": '',
        "ccf": 'A',
        "issn": '0362-5915',
    },
    {
        "name": 'TOG',
        "full": 'ACM Transactions on Graphics',
        "area": '计算机图形学与多媒体 (CG)',
        "homepage": 'https://dl.acm.org/journal/tog',
        "dblp": '',
        "ccf": 'A',
        "issn": '0730-0301',
    },
    {
        "name": 'TOIS',
        "full": 'ACM Transactions on Information Systems',
        "area": '数据库/数据挖掘/内容检索 (DB)',
        "homepage": 'https://dl.acm.org/journal/tois',
        "dblp": '',
        "ccf": 'A',
        "issn": '1046-8188',
    },
    {
        "name": 'TOPLAS',
        "full": 'ACM Transactions on Programming Languages and Systems',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://dl.acm.org/journal/toplas',
        "dblp": '',
        "ccf": 'A',
        "issn": '0164-0925',
    },
    {
        "name": 'TPAMI',
        "full": 'IEEE Transactions on Pattern Analysis and Machine Intelligence',
        "area": '人工智能 (AI)',
        "homepage": 'https://www.computer.org/csdl/journal/tp',
        "dblp": '',
        "ccf": 'A',
        "issn": '0162-8828',
    },
    {
        "name": 'TPDS',
        "full": 'IEEE Transactions on Parallel and Distributed Systems',
        "area": '计算机体系结构/并行与分布计算/存储系统 (DS)',
        "homepage": 'https://www.computer.org/csdl/journal/td',
        "dblp": '',
        "ccf": 'A',
        "issn": '1045-9219',
    },
    {
        "name": 'TSE',
        "full": 'IEEE Transactions on Software Engineering',
        "area": '软件工程/系统软件/程序设计语言 (SE)',
        "homepage": 'https://www.computer.org/csdl/journal/ts',
        "dblp": '',
        "ccf": 'A',
        "issn": '0098-5589',
    },
]


def catalog(kind: str | None = None) -> list[dict[str, str]]:
    """Return catalogue entries; ``kind`` is ``"conference"`` / ``"journal"`` / ``None`` (both)."""
    if kind == "conference":
        return list(CCF_A_CONFERENCES)
    if kind == "journal":
        return list(CCF_A_JOURNALS)
    return list(CCF_A_CONFERENCES) + list(CCF_A_JOURNALS)
